### ISSUE TITLE
failed to compile with varnish 4.1.0-tp1

### ISSUE THREAD

**Issue by llavaud** [varnish/libvmod-header#13]
Hello,

The module failed to compile with varnish 4.1.0-tp1 on debian wheezy amd64:

[dev]build02:~/libvmod-header# make
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /root/libvmod-header/missing --run autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory `/root/libvmod-header'
Making all in src
make[2]: Entering directory`/root/libvmod-header/src'
/bin/bash ../libtool --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Werror   -g -O2 -Wextra -Wno-missing-field-initializers -Wno-sign-compare -MT vmod_header.lo -MD -MP -MF .deps/vmod_header.Tpo -c -o vmod_header.lo vmod_header.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Werror -g -O2 -Wextra -Wno-missing-field-initializers -Wno-sign-compare -MT vmod_header.lo -MD -MP -MF .deps/vmod_header.Tpo -c vmod_header.c  -fPIC -DPIC -o .libs/vmod_header.o
vmod_header.c:68:1: error: static declaration of 'VRT_selecthttp' follows non-static declaration
In file included from vmod_header.c:32:0:
/usr/include/varnish/vrt.h:259:14: note: previous declaration of 'VRT_selecthttp' was here
make[2]: **\* [vmod_header.lo] Error 1
make[2]: Leaving directory `/root/libvmod-header/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/root/libvmod-header'
make: **\* [all] Error 2

**Comment by aondio** [comment]
Hi,
the VMOD doesn't build against Varnish4.1 because it hasn't be ported yet.

**Comment by laurentl92** [comment]
thanks for the patch it works great.

you can't fix this one too ? ;)
https://github.com/lkarsten/libvmod-cookie/issues/37

i need both of header and cookie vmods.
